// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLPKxnbTJNgHyUPbPjvd0EzLPQR9pAh14',
    appId: '1:90169853070:web:286a75850681b45b06b5df',
    messagingSenderId: '90169853070',
    projectId: 'responseone-1501770779021',
    authDomain: 'responseone-1501770779021.firebaseapp.com',
    storageBucket: 'responseone-1501770779021.firebasestorage.app',
    measurementId: 'G-N1FHN6F4G4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVVY01PlmdomzVA2sX5M4O1fSxtv34dJA',
    appId: '1:90169853070:android:c0403ac934a5c55a06b5df',
    messagingSenderId: '90169853070',
    projectId: 'responseone-1501770779021',
    storageBucket: 'responseone-1501770779021.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMkAb7DDJVvJIv3mo7G926dglcdyQ_RUQ',
    appId: '1:90169853070:ios:853e4a759502213606b5df',
    messagingSenderId: '90169853070',
    projectId: 'responseone-1501770779021',
    storageBucket: 'responseone-1501770779021.firebasestorage.app',
    iosBundleId: 'com.securehub.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMkAb7DDJVvJIv3mo7G926dglcdyQ_RUQ',
    appId: '1:90169853070:ios:853e4a759502213606b5df',
    messagingSenderId: '90169853070',
    projectId: 'responseone-1501770779021',
    storageBucket: 'responseone-1501770779021.firebasestorage.app',
    iosBundleId: 'com.securehub.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLPKxnbTJNgHyUPbPjvd0EzLPQR9pAh14',
    appId: '1:90169853070:web:63353dbb2b1da59a06b5df',
    messagingSenderId: '90169853070',
    projectId: 'responseone-1501770779021',
    authDomain: 'responseone-1501770779021.firebaseapp.com',
    storageBucket: 'responseone-1501770779021.firebasestorage.app',
    measurementId: 'G-9PEF5R5F7H',
  );

}