# Generated by Django 5.2.12 on 2026-03-25 15:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('country', models.CharField(blank=True, max_length=120)),
                ('hik_site_id', models.CharField(max_length=128, unique=True)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AlarmPanelDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('serial_number', models.CharField(max_length=128, unique=True)),
                ('hik_device_id', models.CharField(max_length=128, unique=True)),
                ('device_type', models.CharField(choices=[('panel', 'Panel')], default='panel', max_length=32)),
                ('is_online', models.BooleanField(default=False)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='sites.site')),
            ],
        ),
        migrations.CreateModel(
            name='Subsystem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('hik_subsystem_id', models.CharField(max_length=128, unique=True)),
                ('subsystem_number', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('disarmed', 'Disarmed'), ('armed', 'Armed'), ('stay', 'Stay Armed'), ('alarm', 'Alarm')], default='disarmed', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsystems', to='sites.alarmpaneldevice')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsystems', to='sites.site')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerSiteAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager'), ('viewer', 'Viewer')], default='owner', max_length=16)),
                ('can_control_alarm', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_list', to='sites.site')),
            ],
            options={
                'unique_together': {('user', 'site')},
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('zone_number', models.PositiveIntegerField()),
                ('state', models.CharField(choices=[('normal', 'Normal'), ('open', 'Open'), ('alarm', 'Alarm'), ('bypassed', 'Bypassed')], default='normal', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subsystem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='sites.subsystem')),
            ],
            options={
                'unique_together': {('subsystem', 'zone_number')},
            },
        ),
    ]
