# Generated by Django 5.2.12 on 2026-03-25 20:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('serial_number', models.CharField(max_length=128, unique=True)),
                ('hik_device_id', models.CharField(max_length=128, unique=True)),
                ('device_type', models.CharField(choices=[('nvr', 'NVR'), ('ip_camera', 'IP Camera')], default='nvr', max_length=32)),
                ('is_online', models.BooleanField(default=False)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_devices', to='sites.site')),
            ],
        ),
        migrations.CreateModel(
            name='VideoChannel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('hik_channel_id', models.CharField(max_length=128, unique=True)),
                ('channel_number', models.PositiveIntegerField(default=1)),
                ('is_online', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='sites.videodevice')),
            ],
            options={
                'unique_together': {('device', 'channel_number')},
            },
        ),
    ]
