# Generated by Django 5.2.12 on 2026-03-25 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_videodevice_videochannel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videodevice',
            name='site',
        ),
        migrations.DeleteModel(
            name='VideoChannel',
        ),
        migrations.DeleteModel(
            name='VideoDevice',
        ),
    ]
