# Generated by Django 5.2.12 on 2026-03-28 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0005_health_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarmpaneldevice',
            name='hik_device_sub_category',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subsystem',
            name='delay_time_remaining',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zone',
            name='charge_value',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
