# Generated by Django 5.2.12 on 2026-03-30 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0008_zone_device_number_detector_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
