# Generated by Django 5.2.12 on 2026-03-30 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0009_zone_last_seen_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='is_online',
            field=models.BooleanField(default=True),
        ),
    ]
