# Generated by Django 5.2.12 on 2026-04-07 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0010_zone_is_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarmpaneldevice',
            name='firmware_version',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='alarmpaneldevice',
            name='hardware_version',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='alarmpaneldevice',
            name='model_number',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
