# Generated by Django 5.2.12 on 2026-04-08 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0012_site_latitude_site_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='primary_industry',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='site',
            name='secondary_industry',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='site',
            name='state',
            field=models.CharField(blank=True, help_text='State/Province/Region', max_length=120),
        ),
    ]
