# Generated by Django 5.2.13 on 2026-04-22 09:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0015_zone_access_module_type_zone_diagnostics_result_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('monthly_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('grace_period_days', models.PositiveSmallIntegerField(default=7)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['monthly_rate'],
            },
        ),
        migrations.AddField(
            model_name='subscription',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='sites.subscriptionpackage'),
        ),
    ]
