# Generated by Codex on 2026-04-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0016_subscription_packages"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionpayment",
            name="method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("cash", "Cash"),
                    ("mobile_money", "Mobile Money"),
                    ("bank_transfer", "Bank Transfer"),
                    ("card", "Card"),
                    ("other", "Other"),
                ],
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="subscriptionpayment",
            name="reference",
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
