# Generated by Django 5.2.12 on 2026-04-27 12:35

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0017_subscriptionpayment_method_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionpackage',
            name='emergency_monthly_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='subscriptionpackage',
            name='includes_emergency_service',
            field=models.BooleanField(default=False),
        ),
    ]
