# Generated by Django 5.2.12 on 2026-05-11 21:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guarding', '0001_initial'),
        ('sites', '0019_merge_0018_hiksitedevice_0018_subscriptionpackage_emergency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuardingEventLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, max_length=80)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], db_index=True, default='info', max_length=16)),
                ('source', models.CharField(choices=[('system', 'System'), ('console', 'Console'), ('mobile', 'Mobile'), ('api', 'API')], db_index=True, default='system', max_length=16)),
                ('title', models.CharField(max_length=180)),
                ('message', models.TextField(blank=True)),
                ('object_label', models.CharField(blank=True, db_index=True, max_length=80)),
                ('object_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('unique_key', models.CharField(blank=True, max_length=160, null=True, unique=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guarding_workflow_events', to=settings.AUTH_USER_MODEL)),
                ('guard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_events', to='guarding.guardprofile')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guarding_workflow_events', to='sites.site')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['severity', '-created_at'], name='guard_event_sev_time_idx'), models.Index(fields=['object_label', 'object_id'], name='guard_event_object_idx')],
            },
        ),
    ]
