# Generated by Django 5.2.14 on 2026-05-11 22:22

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guarding', '0002_guardingeventlog'),
        ('sites', '0019_merge_0018_hiksitedevice_0018_subscriptionpackage_emergency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuardEquipmentIssue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=160)),
                ('item_code', models.CharField(blank=True, max_length=80)),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('issued', 'Issued'), ('returned', 'Returned'), ('lost', 'Lost'), ('damaged', 'Damaged')], db_index=True, default='issued', max_length=24)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_issues', to='guarding.guardprofile')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_guard_equipment', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='GuardOffboardingChecklist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('equipment_returned', models.BooleanField(default=False)),
                ('documents_archived', models.BooleanField(default=False)),
                ('access_revoked', models.BooleanField(default=False)),
                ('final_timesheet_approved', models.BooleanField(default=False)),
                ('exit_notes', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_guard_offboardings', to=settings.AUTH_USER_MODEL)),
                ('guard', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='offboarding_checklist', to='guarding.guardprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('report_type', models.CharField(choices=[('daily_activity', 'Daily Activity'), ('incident', 'Incident'), ('maintenance', 'Maintenance'), ('visitor', 'Visitor'), ('parking', 'Parking'), ('pass_on', 'Pass-on'), ('other', 'Other')], db_index=True, max_length=32)),
                ('schema', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_guard_report_templates', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guard_report_templates', to='sites.site')),
            ],
            options={
                'ordering': ['report_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ClientPortalAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('viewer', 'Viewer'), ('manager', 'Manager'), ('approver', 'Approver')], default='viewer', max_length=24)),
                ('can_view_reports', models.BooleanField(default=True)),
                ('can_view_patrols', models.BooleanField(default=True)),
                ('can_view_attendance', models.BooleanField(default=True)),
                ('can_acknowledge_reports', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guard_client_access', to='sites.site')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guard_client_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['site__name', 'user__username'],
                'unique_together': {('user', 'site')},
            },
        ),
        migrations.CreateModel(
            name='GuardAvailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('availability_type', models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable'), ('preferred', 'Preferred')], default='available', max_length=24)),
                ('starts_at', models.DateTimeField(db_index=True)),
                ('ends_at', models.DateTimeField(db_index=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_guard_availability', to=settings.AUTH_USER_MODEL)),
                ('guard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='guarding.guardprofile')),
            ],
            options={
                'ordering': ['starts_at'],
                'indexes': [models.Index(fields=['guard', 'starts_at', 'ends_at'], name='guard_availability_time_idx')],
            },
        ),
        migrations.CreateModel(
            name='GuardContract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('ended', 'Ended')], db_index=True, default='draft', max_length=24)),
                ('starts_on', models.DateField()),
                ('ends_on', models.DateField(blank=True, null=True)),
                ('bill_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pay_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('overtime_multiplier', models.DecimalField(decimal_places=2, default=1.5, max_digits=5)),
                ('sla_minutes', models.PositiveIntegerField(default=30)),
                ('required_qualifications', models.JSONField(blank=True, default=list)),
                ('escalation_contacts', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='guarding.guardpost')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guard_contracts', to='sites.site')),
            ],
            options={
                'ordering': ['site__name', 'name'],
                'indexes': [models.Index(fields=['status', 'starts_on'], name='guard_contract_status_idx')],
            },
        ),
        migrations.CreateModel(
            name='GuardTimesheet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateTimeField(db_index=True)),
                ('period_end', models.DateTimeField(db_index=True)),
                ('regular_minutes', models.PositiveIntegerField(default=0)),
                ('overtime_minutes', models.PositiveIntegerField(default=0)),
                ('pay_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bill_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('exported', 'Exported')], db_index=True, default='draft', max_length=24)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('export_reference', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_guard_timesheets', to=settings.AUTH_USER_MODEL)),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='timesheet', to='guarding.shiftassignment')),
                ('guard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheets', to='guarding.guardprofile')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timesheets', to='guarding.guardpost')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guard_timesheets', to='sites.site')),
            ],
            options={
                'ordering': ['-period_start'],
                'indexes': [models.Index(fields=['site', 'status', 'period_start'], name='guard_timesheet_site_idx')],
            },
        ),
        migrations.CreateModel(
            name='GuardTrainingRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('provider', models.CharField(blank=True, max_length=160)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('completed', 'Completed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], db_index=True, default='planned', max_length=24)),
                ('completed_on', models.DateField(blank=True, null=True)),
                ('expires_on', models.DateField(blank=True, db_index=True, null=True)),
                ('certificate_number', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_records', to='guarding.guardprofile')),
            ],
            options={
                'ordering': ['expires_on', 'name'],
                'indexes': [models.Index(fields=['status', 'expires_on'], name='guard_training_exp_idx')],
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('starts_at', models.DateTimeField(db_index=True)),
                ('ends_at', models.DateTimeField(db_index=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=24)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='guarding.guardprofile')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_guard_leave_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-starts_at'],
                'indexes': [models.Index(fields=['guard', 'status', 'starts_at'], name='guard_leave_status_idx')],
            },
        ),
        migrations.CreateModel(
            name='ShiftTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('required_guards', models.PositiveSmallIntegerField(default=1)),
                ('days_of_week', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_templates', to='guarding.guardpost')),
            ],
            options={
                'ordering': ['post', 'name'],
                'unique_together': {('post', 'name')},
            },
        ),
    ]
