# Generated by Django 5.2.13 on 2026-05-24 09:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guarding', '0004_guardinvoice_guardinvoiceline_shiftswaprequest_and_more'),
        ('sites', '0019_merge_0018_hiksitedevice_0018_subscriptionpackage_emergency'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuardingPrivacySettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('location_ping_retention_days', models.PositiveIntegerField(default=90)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Guarding privacy settings',
            },
        ),
        migrations.CreateModel(
            name='SiteGuardDispatchPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('auto_from_emergency', models.BooleanField(default=True)),
                ('auto_from_alarm', models.BooleanField(default=False)),
                ('auto_assign_nearest', models.BooleanField(default=False)),
                ('alarm_severities', models.JSONField(blank=True, default=list, help_text="Alarm severities that trigger dispatch, e.g. ['critical','high']. Empty = all when auto_from_alarm is on.")),
                ('default_priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='high', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guard_dispatch_policy', to='sites.site')),
            ],
            options={
                'verbose_name_plural': 'Site guard dispatch policies',
            },
        ),
    ]
