# Generated by Django 5.2.13 on 2026-06-01 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guarding", "0009_clientportalaccess_can_view_guards"),
        ("sites", "0020_operations_zone"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="guardingassetpolicy",
            name="guard_asset_policy_site_xor_post",
        ),
        migrations.AddConstraint(
            model_name="guardingassetpolicy",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("post__isnull", True), ("site__isnull", False)),
                    models.Q(("post__isnull", False), ("site__isnull", True)),
                    _connector="OR",
                ),
                name="guard_asset_policy_site_xor_post",
            ),
        ),
    ]
