# Generated by Django 5.2.13 on 2026-05-24 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0006_alter_broadcastmessage_recipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcastmessage',
            name='push_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
