# Generated by Django 5.2.12 on 2026-03-28 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarmevent',
            name='occurred_at',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='armdisarmcommand',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
