# Generated by Django 5.2.12 on 2026-03-30 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarms', '0002_alter_alarmevent_occurred_at_and_more'),
        ('sites', '0009_zone_last_seen_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarmevent',
            name='subsystem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='sites.subsystem'),
        ),
        migrations.AlterField(
            model_name='alarmevent',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='sites.zone'),
        ),
    ]
