# Generated by Django 5.2.12 on 2026-04-04 00:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarms', '0003_alter_alarmevent_subsystem_alter_alarmevent_zone'),
        ('sites', '0010_zone_is_online'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alarmevent',
            name='acknowledged',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='alarmevent',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alarmevent',
            name='acknowledged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alarmevent',
            name='device_serial',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='alarmevent',
            name='event_category',
            field=models.CharField(choices=[('alarm', 'Alarm'), ('arm', 'Arm/Disarm'), ('system', 'System'), ('health', 'Health'), ('info', 'Info')], db_index=True, default='info', max_length=32),
        ),
        migrations.AddField(
            model_name='alarmevent',
            name='event_code',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='alarmevent',
            name='severity',
            field=models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], db_index=True, default='low', max_length=16),
        ),
        migrations.AddField(
            model_name='armdisarmcommand',
            name='device_serial',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='armdisarmcommand',
            name='executed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationdelivery',
            name='last_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='notificationdelivery',
            name='provider',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='notificationdelivery',
            name='retry_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='alarmevent',
            name='source_event_id',
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='alarmevent',
            name='subsystem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='sites.subsystem'),
        ),
        migrations.AlterField(
            model_name='alarmevent',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='sites.zone'),
        ),
        migrations.AddIndex(
            model_name='alarmevent',
            index=models.Index(fields=['site', '-occurred_at'], name='alarm_event_site_time_idx'),
        ),
        migrations.AddIndex(
            model_name='alarmevent',
            index=models.Index(fields=['site', 'source_event_id'], name='alarm_event_site_hash_idx'),
        ),
        migrations.AddIndex(
            model_name='alarmevent',
            index=models.Index(fields=['event_type'], name='alarm_event_type_idx'),
        ),
        migrations.AddConstraint(
            model_name='alarmevent',
            constraint=models.UniqueConstraint(condition=models.Q(('source_event_id__gt', '')), fields=('site', 'source_event_id'), name='unique_event_per_site'),
        ),
        migrations.AddConstraint(
            model_name='armdisarmcommand',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__gt', '')), fields=('site', 'idempotency_key'), name='unique_command_per_site'),
        ),
    ]
