# Generated by Django 5.2.12 on 2026-04-06 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarms', '0004_alarm_event_category_severity_ack_dedup_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarmevent',
            name='performed_by',
            field=models.CharField(blank=True, db_index=True, max_length=128, verbose_name='User'),
        ),
    ]
